[workspace]

members = [
  "cess-hashers",
  "cess-proofs",
  "cess-proofs-param",
  "cess-proofs-tooling",
  "cess-fr32",
  "storage-proofs-core",
  "storage-proofs-porep",
  "storage-proofs-post",
  "sha2raw",
]
